### PR TITLE
fix(deps): upgrade dependencies to fix vulnerabilities

### LINKED ISSUE #20: Vulnerable `debug` package
Hey there! :wave: 

I use this package in few places, and in one of them NSP reports that `debug` is older version that has ReDDoS vulnerability.

I am seeing that here is no `debug` as dependency but for some reason the NSP report mention that package, so.. don't know.

https://nodesecurity.io/orgs/tunnckocore-dev/projects/b8ccbfa6-282e-4360-aee5-1497dc059e6b/4

Probably some of your deps uses old debug? Don't know. How can we fix such issues? Probably to install `debug` in my package temporary?

### PR DESCRIPTION
**Pull request by rbardini**
#### What this PR does

- Upgrade dependencies to fix `npm audit` security vulnerabilities
- Fix inquirer and linting issues

Closes #20.

### CODE REVIEW

**Comment by rbardini** [comment]
@bahmutov have you had a chance to review these changes, or do you need any help maintaining this project? These security vulnerabilities impact several projects.

**Comment by vitorarins** [comment]
Hey @bahmutov, thank you for this project :smile: 
Can you take a look on this PR? It looks like it's impacting a lot of other projects.

**Comment by bahmutov** [comment]
Need to fix the release, uggh

**Comment by bahmutov** [comment]
Done - released v4.0.5

**Pull request merged**
