### PR TITLE
fix(postinstall): remove postinstall script

### LINKED ISSUE #23: Postinstall script interferes with semantic-release config
Hi, I had a really annoying debug session :/

If installing `simple-commit-message` with `semantic-release` and configuring `semantic-release` in a `.releaserc` file the post-install script of this plugin modifies the `package.json` file each time I am doing an npm install (which is every build, as it thinks there is no release configured).
The problem now is that the release config in the `package.json` takes precedence over the `.releaserc` config and in this way uses the standard configuration every build. 

In order to solve this problem there are multiple ways: 

1. (My favorite) Remove the Postinstall script. 
   - Just provide a configuration example in the README.md as every other plugin or package. 
   - Adding a `"release"` option isn't that hard. (Maybe I can refactor the `postinstall` script into a cmd command, so it is still easy to install) 

2. Make it agnostic to `.releaserc` files. 
   - Maybe there are some other config formats I or We couldn't think of, than we will start over again. 

3. At least provide a Environment variable to not execute the postinstall script. 

Please choose one of the above actions and I will try my best to provide a PR for it. Thanks!

### PR DESCRIPTION
**Pull request by rbardini**
Automatically adding a `release` section to `package.json` during install makes it impossible to use simple-commit-message with a `.releaserc` or `release.config.js` file, especially in a CI environment, as `package.json` takes precedence over configuration files.

This breaking change removes the `postinstall` script so that simple-commit-message won't automatically add itself to the `release` section of `package.json` during install anymore.

Closes #23.

### CODE REVIEW

**Comment by rbardini** [comment]
@bahmutov any feedback on this?

**Comment by tujoworker** [comment]
I really would appreciate the release of this PR 🙏

**Comment by bahmutov** [comment]
Ha, I messed up myself, and used `BREAKING CHANGE` in the body of the commit instead of `break` in the subject, ohh well...

**Comment by tujoworker** [comment]
no problem. For existing user I does not matter I guess. And for new users, they will do set it up manually anyway.

**Pull request merged**
